In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/investments_VC.csv", encoding='latin-1')
df

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df = df.drop(columns=["permalink", 
                      "homepage_url", 
                      "post_ipo_equity",
                      "post_ipo_debt",
                      "last_funding_at",
                      "founded_year",
                      "founded_month",
                      "founded_quarter",
                      "category_list",
                      "state_code", 
                      "city"])
df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,"17,50,000",acquired,USA,New York City,1.0,2012-06-01,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,&TV Communications,Games,"40,00,000",operating,USA,Los Angeles,2.0,NaN,2010-06-04,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,'Rock' Your Paper,Publishing,"40,000",operating,EST,Tallinn,1.0,2012-10-26,2012-08-09,40000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(In)Touch Network,Electronics,"15,00,000",operating,GBR,London,1.0,2011-04-01,2011-04-01,1500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,"60,000",operating,USA,Dallas,2.0,2014-01-01,2014-08-17,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print((df.isnull().mean() * 100).sort_values(ascending=False))

founded_at              28.990312
country_code            18.655837
region                  18.655837
 market                 16.252256
status                  11.364055
name                     8.945740
private_equity           8.943898
round_G                  8.943898
round_F                  8.943898
round_E                  8.943898
round_D                  8.943898
round_C                  8.943898
round_B                  8.943898
round_A                  8.943898
product_crowdfunding     8.943898
secondary_market         8.943898
debt_financing           8.943898
grant                    8.943898
angel                    8.943898
convertible_note         8.943898
undisclosed              8.943898
equity_crowdfunding      8.943898
venture                  8.943898
seed                     8.943898
first_funding_at         8.943898
funding_rounds           8.943898
 funding_total_usd       8.943898
round_H                  8.943898
dtype: float64

In [5]:
print(df.dtypes)

name                        str
 market                     str
 funding_total_usd          str
status                      str
country_code                str
region                      str
funding_rounds          float64
founded_at                  str
first_funding_at            str
seed                    float64
venture                 float64
equity_crowdfunding     float64
undisclosed             float64
convertible_note        float64
debt_financing          float64
angel                   float64
grant                   float64
private_equity          float64
secondary_market        float64
product_crowdfunding    float64
round_A                 float64
round_B                 float64
round_C                 float64
round_D                 float64
round_E                 float64
round_F                 float64
round_G                 float64
round_H                 float64
dtype: object

In [6]:
for c in ["founded_at", "first_funding_at"]:
    df[c] = pd.to_datetime(df[c], errors="coerce")

In [7]:
df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,"17,50,000",acquired,USA,New York City,1.0,2012-06-01,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,&TV Communications,Games,"40,00,000",operating,USA,Los Angeles,2.0,NaT,2010-06-04,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,'Rock' Your Paper,Publishing,"40,000",operating,EST,Tallinn,1.0,2012-10-26,2012-08-09,40000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(In)Touch Network,Electronics,"15,00,000",operating,GBR,London,1.0,2011-04-01,2011-04-01,1500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,"60,000",operating,USA,Dallas,2.0,2014-01-01,2014-08-17,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(df.groupby(df["founded_at"].isna())["status"].value_counts(normalize=True))

founded_at  status
False       operating    0.867892
            acquired     0.079073
            closed       0.053034
True        operating    0.873856
            acquired     0.068268
            closed       0.057876
Name: proportion, dtype: float64

In [9]:
df = df.dropna(subset=["founded_at", "status"])
df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,"17,50,000",acquired,USA,New York City,1.0,2012-06-01,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,'Rock' Your Paper,Publishing,"40,000",operating,EST,Tallinn,1.0,2012-10-26,2012-08-09,40000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(In)Touch Network,Electronics,"15,00,000",operating,GBR,London,1.0,2011-04-01,2011-04-01,1500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,"60,000",operating,USA,Dallas,2.0,2014-01-01,2014-08-17,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0-6.com,Curated Web,"20,00,000",operating,NaN,NaN,1.0,2007-01-01,2008-03-19,0.0,...,0.0,0.0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49430,Zyraz Technology,Biotechnology,"1,54,19,877",closed,MYS,MYS - Other,4.0,1994-01-01,2008-01-01,0.0,...,0.0,0.0,7991547.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49432,Zytoprotec,Biotechnology,"26,86,600",operating,AUT,Vienna,1.0,2007-01-01,2013-01-29,0.0,...,0.0,0.0,2686600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49433,Zzish,Education,"3,20,000",operating,GBR,London,1.0,2013-01-28,2014-03-24,320000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49435,Zzzzapp Wireless ltd.,Web Development,"97,398",operating,HRV,Split,5.0,2012-05-13,2011-11-01,71525.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,[x+1],Enterprise Software,"4,50,00,000",operating,USA,New York City,4.0,1999-01-01,2008-06-01,0.0,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df.columns = df.columns.str.strip()

In [11]:
df["country_code"] = df["country_code"].fillna("Unknown")
df["region"] = df["region"].fillna("Unknown")
df["market"] = df["market"].fillna("Unknown")

In [12]:
print((df.isnull().mean() * 100).sort_values(ascending=False))

name                    0.002657
market                  0.000000
round_G                 0.000000
round_F                 0.000000
round_E                 0.000000
round_D                 0.000000
round_C                 0.000000
round_B                 0.000000
round_A                 0.000000
product_crowdfunding    0.000000
secondary_market        0.000000
private_equity          0.000000
grant                   0.000000
angel                   0.000000
debt_financing          0.000000
convertible_note        0.000000
undisclosed             0.000000
equity_crowdfunding     0.000000
venture                 0.000000
seed                    0.000000
first_funding_at        0.000000
founded_at              0.000000
funding_rounds          0.000000
region                  0.000000
country_code            0.000000
status                  0.000000
funding_total_usd       0.000000
round_H                 0.000000
dtype: float64

In [13]:
df = df.dropna(subset=["name"])
df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,"17,50,000",acquired,USA,New York City,1.0,2012-06-01,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,'Rock' Your Paper,Publishing,"40,000",operating,EST,Tallinn,1.0,2012-10-26,2012-08-09,40000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(In)Touch Network,Electronics,"15,00,000",operating,GBR,London,1.0,2011-04-01,2011-04-01,1500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,"60,000",operating,USA,Dallas,2.0,2014-01-01,2014-08-17,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0-6.com,Curated Web,"20,00,000",operating,Unknown,Unknown,1.0,2007-01-01,2008-03-19,0.0,...,0.0,0.0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49430,Zyraz Technology,Biotechnology,"1,54,19,877",closed,MYS,MYS - Other,4.0,1994-01-01,2008-01-01,0.0,...,0.0,0.0,7991547.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49432,Zytoprotec,Biotechnology,"26,86,600",operating,AUT,Vienna,1.0,2007-01-01,2013-01-29,0.0,...,0.0,0.0,2686600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49433,Zzish,Education,"3,20,000",operating,GBR,London,1.0,2013-01-28,2014-03-24,320000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49435,Zzzzapp Wireless ltd.,Web Development,"97,398",operating,HRV,Split,5.0,2012-05-13,2011-11-01,71525.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,[x+1],Enterprise Software,"4,50,00,000",operating,USA,New York City,4.0,1999-01-01,2008-06-01,0.0,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
print(df.dtypes)

name                               str
market                             str
funding_total_usd                  str
status                             str
country_code                       str
region                             str
funding_rounds                 float64
founded_at              datetime64[us]
first_funding_at        datetime64[us]
seed                           float64
venture                        float64
equity_crowdfunding            float64
undisclosed                    float64
convertible_note               float64
debt_financing                 float64
angel                          float64
grant                          float64
private_equity                 float64
secondary_market               float64
product_crowdfunding           float64
round_A                        float64
round_B                        float64
round_C                        float64
round_D                        float64
round_E                        float64
round_F                        float64
round_G                        float64
round_H                        float64
dtype: object

In [15]:
df["funding_total_usd"] = pd.to_numeric(
    df["funding_total_usd"].astype(str).str.replace(",", "").str.strip(),
    errors="coerce"
)

df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000.0,acquired,USA,New York City,1.0,2012-06-01,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,'Rock' Your Paper,Publishing,40000.0,operating,EST,Tallinn,1.0,2012-10-26,2012-08-09,40000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(In)Touch Network,Electronics,1500000.0,operating,GBR,London,1.0,2011-04-01,2011-04-01,1500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,60000.0,operating,USA,Dallas,2.0,2014-01-01,2014-08-17,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0-6.com,Curated Web,2000000.0,operating,Unknown,Unknown,1.0,2007-01-01,2008-03-19,0.0,...,0.0,0.0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49430,Zyraz Technology,Biotechnology,15419877.0,closed,MYS,MYS - Other,4.0,1994-01-01,2008-01-01,0.0,...,0.0,0.0,7991547.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49432,Zytoprotec,Biotechnology,2686600.0,operating,AUT,Vienna,1.0,2007-01-01,2013-01-29,0.0,...,0.0,0.0,2686600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49433,Zzish,Education,320000.0,operating,GBR,London,1.0,2013-01-28,2014-03-24,320000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49435,Zzzzapp Wireless ltd.,Web Development,97398.0,operating,HRV,Split,5.0,2012-05-13,2011-11-01,71525.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,[x+1],Enterprise Software,45000000.0,operating,USA,New York City,4.0,1999-01-01,2008-06-01,0.0,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
print((df.isnull().mean() * 100).sort_values(ascending=False))

funding_total_usd       16.460741
name                     0.000000
angel                    0.000000
round_G                  0.000000
round_F                  0.000000
round_E                  0.000000
round_D                  0.000000
round_C                  0.000000
round_B                  0.000000
round_A                  0.000000
product_crowdfunding     0.000000
secondary_market         0.000000
private_equity           0.000000
grant                    0.000000
debt_financing           0.000000
market                   0.000000
convertible_note         0.000000
undisclosed              0.000000
equity_crowdfunding      0.000000
venture                  0.000000
seed                     0.000000
first_funding_at         0.000000
founded_at               0.000000
funding_rounds           0.000000
region                   0.000000
country_code             0.000000
status                   0.000000
round_H                  0.000000
dtype: float64

In [17]:
df["funding_total_usd"] = df["funding_total_usd"].fillna(0)
df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000.0,acquired,USA,New York City,1.0,2012-06-01,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,'Rock' Your Paper,Publishing,40000.0,operating,EST,Tallinn,1.0,2012-10-26,2012-08-09,40000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(In)Touch Network,Electronics,1500000.0,operating,GBR,London,1.0,2011-04-01,2011-04-01,1500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,60000.0,operating,USA,Dallas,2.0,2014-01-01,2014-08-17,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0-6.com,Curated Web,2000000.0,operating,Unknown,Unknown,1.0,2007-01-01,2008-03-19,0.0,...,0.0,0.0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49430,Zyraz Technology,Biotechnology,15419877.0,closed,MYS,MYS - Other,4.0,1994-01-01,2008-01-01,0.0,...,0.0,0.0,7991547.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49432,Zytoprotec,Biotechnology,2686600.0,operating,AUT,Vienna,1.0,2007-01-01,2013-01-29,0.0,...,0.0,0.0,2686600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49433,Zzish,Education,320000.0,operating,GBR,London,1.0,2013-01-28,2014-03-24,320000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49435,Zzzzapp Wireless ltd.,Web Development,97398.0,operating,HRV,Split,5.0,2012-05-13,2011-11-01,71525.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,[x+1],Enterprise Software,45000000.0,operating,USA,New York City,4.0,1999-01-01,2008-06-01,0.0,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
print(df.duplicated().sum())

0

In [19]:
df[df.duplicated(subset=["name"], keep=False)].sort_values("name")

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
4149,AYOXXA Biosystems,Biotechnology,12145503.0,operating,DEU,Cologne,1.0,2010-01-01,2014-07-23,0.0,...,0.0,0.0,0.0,12145503.0,0.0,0.0,0.0,0.0,0.0,0.0
4150,AYOXXA Biosystems,Biotechnology,14081347.0,operating,DEU,Cologne,1.0,2010-01-01,2014-12-02,14081347.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1131,Adometry By Google,Displays,29125000.0,acquired,USA,Austin,4.0,2005-01-01,2007-02-07,0.0,...,0.0,0.0,5000000.0,10025000.0,6000000.0,8100000.0,0.0,0.0,0.0,0.0
1132,Adometry By Google,Displays,450000.0,acquired,Unknown,Unknown,1.0,2006-01-01,2010-01-12,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3762,August,Home Automation,10000000.0,operating,USA,SF Bay Area,2.0,2013-01-01,2013-01-01,0.0,...,0.0,0.0,8000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20642,inMarket,Online Reservations,1000000.0,operating,USA,Los Angeles,1.0,2010-04-01,2010-05-01,0.0,...,0.0,0.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36415,rumr,Identity,0.0,operating,Unknown,Unknown,1.0,2013-10-01,2013-11-01,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36414,rumr,Real Estate,800000.0,operating,USA,New York City,1.0,2013-08-01,2013-12-03,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44237,trippiece,Curated Web,2000000.0,operating,JPN,Tokyo,2.0,2011-03-11,2011-05-16,0.0,...,0.0,0.0,0.0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0
44236,trippiece,Travel,2144502.0,operating,JPN,Tokyo,3.0,2011-01-01,2011-05-16,112946.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
df = df.sort_values("funding_total_usd", ascending=False)
df = df.drop_duplicates(subset=["name", "founded_at", "country_code"], keep="first")

In [21]:
df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
45815,Verizon Communications,Mobile,3.007950e+10,operating,USA,New York City,5.0,1983-10-07,2010-01-26,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8664,Clearwire,Internet,5.700000e+09,acquired,USA,Seattle,4.0,2003-10-01,2008-05-06,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7977,Charter Communications,Unknown,5.162513e+09,operating,USA,Hartford,2.0,1993-01-01,2009-11-21,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15315,First Data Corporation,Trading,3.500000e+09,operating,USA,Atlanta,1.0,1971-01-01,2014-07-03,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38289,sigmacare,Health and Wellness,2.600000e+09,operating,USA,New York City,1.0,2005-01-01,2013-07-29,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31022,Overblog,Blogging Platforms,0.000000e+00,acquired,FRA,Toulouse,1.0,2004-02-14,2006-08-01,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31023,Overcart,Retail,0.000000e+00,operating,Unknown,Unknown,1.0,2012-01-01,2014-06-24,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5077,"BiJoTi, Inc.",Unknown,0.000000e+00,operating,Unknown,Unknown,1.0,2014-06-01,2014-11-01,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11399,dentaZOOM,Health and Wellness,0.000000e+00,operating,DEU,Berlin,1.0,2012-01-01,2013-10-24,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18659,HealthClinicPlus,Unknown,0.000000e+00,operating,IRL,Tralee,1.0,2011-01-01,2013-01-22,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
print(df.isna().sum())

name                    0
market                  0
funding_total_usd       0
status                  0
country_code            0
region                  0
funding_rounds          0
founded_at              0
first_funding_at        0
seed                    0
venture                 0
equity_crowdfunding     0
undisclosed             0
convertible_note        0
debt_financing          0
angel                   0
grant                   0
private_equity          0
secondary_market        0
product_crowdfunding    0
round_A                 0
round_B                 0
round_C                 0
round_D                 0
round_E                 0
round_F                 0
round_G                 0
round_H                 0
dtype: int64

In [23]:
print(df.dtypes)

name                               str
market                             str
funding_total_usd              float64
status                             str
country_code                       str
region                             str
funding_rounds                 float64
founded_at              datetime64[us]
first_funding_at        datetime64[us]
seed                           float64
venture                        float64
equity_crowdfunding            float64
undisclosed                    float64
convertible_note               float64
debt_financing                 float64
angel                          float64
grant                          float64
private_equity                 float64
secondary_market               float64
product_crowdfunding           float64
round_A                        float64
round_B                        float64
round_C                        float64
round_D                        float64
round_E                        float64
round_F                        float64
round_G                        float64
round_H                        float64
dtype: object

In [24]:
df["status"].unique()

<StringArray>
['operating', 'acquired', 'closed']
Length: 3, dtype: str

In [25]:
print(df["founded_at"].describe())

count                         37628
mean     2007-04-29 14:45:17.125544
min             1636-09-08 00:00:00
25%             2005-12-01 00:00:00
50%             2010-01-01 00:00:00
75%             2012-01-01 00:00:00
max             2014-12-13 00:00:00
Name: founded_at, dtype: object

In [26]:
print((df["founded_at"] < "1900-01-01").sum())
df[df["founded_at"] < "1900-01-01"][["name", "founded_at"]]

68

                                      name founded_at
42686                         The Exchange 1895-07-25
45074               University of Maryland 1856-01-01
23434                           Landis+Gyr 1896-01-01
17815         Great Atlantic & Pacific Tea 1859-01-01
9391                         Commerce Bank 1865-01-01
...                                    ...        ...
45088              University of Rochester 1850-01-01
23385                        Laclede Group 1857-01-01
37798                               Sferra 1891-01-01
4518                              Bayer AG 1863-01-01
3439   Asia Pacific Marine Container Lines 1870-01-05

[68 rows x 2 columns]

In [27]:
df = df[df["founded_at"] >= "1900-01-01"]

In [28]:
df = df.reset_index(drop=True)
df

,name,market,funding_total_usd,status,country_code,region,funding_rounds,founded_at,first_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,Verizon Communications,Mobile,3.007950e+10,operating,USA,New York City,5.0,1983-10-07,2010-01-26,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Clearwire,Internet,5.700000e+09,acquired,USA,Seattle,4.0,2003-10-01,2008-05-06,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Charter Communications,Unknown,5.162513e+09,operating,USA,Hartford,2.0,1993-01-01,2009-11-21,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,First Data Corporation,Trading,3.500000e+09,operating,USA,Atlanta,1.0,1971-01-01,2014-07-03,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,sigmacare,Health and Wellness,2.600000e+09,operating,USA,New York City,1.0,2005-01-01,2013-07-29,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37555,Overblog,Blogging Platforms,0.000000e+00,acquired,FRA,Toulouse,1.0,2004-02-14,2006-08-01,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37556,Overcart,Retail,0.000000e+00,operating,Unknown,Unknown,1.0,2012-01-01,2014-06-24,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37557,"BiJoTi, Inc.",Unknown,0.000000e+00,operating,Unknown,Unknown,1.0,2014-06-01,2014-11-01,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37558,dentaZOOM,Health and Wellness,0.000000e+00,operating,DEU,Berlin,1.0,2012-01-01,2013-10-24,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37559,HealthClinicPlus,Unknown,0.000000e+00,operating,IRL,Tralee,1.0,2011-01-01,2013-01-22,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
df.to_csv("../data/proccessed/clean_investments_VC.csv")